Meteor.methods({
	RemoveOrder:function(id){
		orders.remove({'_id':id});
	},
	UpdateOrders:function(id,obj){
		if(id){
			 orders.update({'_id':id},{$set:obj});
		}
	},
	UpdateOrderStatus:function(id,next){
		orders.update({'_id':id},{$set:{'status':next}});
	}
});
